In [68]:
#importação das bibliotecas
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier,ExtraTreesClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

In [10]:
#importação da base de dados
data = pd.read_csv("CreditCardFraud.csv", sep = ';')
data.head()

Time                   V1                   V2                   V3  \
0   406   -23122265423263,00   195199201064158,00  -160985073229769,00   
1   472   -30435406239976,00  -315730712090228,00   108846277997285,00   
2  4462  -230334956758553,00     1759247460267,00   -0.359744743330052   
3  6986  -439797444171999,00   135836702839758,00   -25928442182573,00   
4  7519   123423504613468,00    30197404207034,00  -430459688479665,00   

                   V4                   V5                   V6  \
0   39979055875468,00   -0.522187864667764  -142654531920595,00   
1   22886436183814,00   135980512966107,00  -106482252298131,00   
2  233024305053917,00   -0.821628328375422  -0.0757875706194599   
3  267978696694832,00  -112813094208956,00  -170653638774951,00   
4  473279513041887,00   362420083055386,00  -135774566315358,00   

                    V7                   V8                   V9  ...  \
0  -253738730624579,00   139165724829804,00  -277008927719433,00  ...   
1    0.325574266158614  -0.0677936531906277   -0.270952836226548  ...   
2    0.562319782266954   -0.399146578487216   -0.238253367661746  ...   
3  -349619729302467,00   -0.248777743025673    -0.24776789948008  ...   
4   171344498787235,00   -0.496358487073991  -128285782036322,00  ...   

                  V21                  V22                 V23  \
0   0.517232370861764  -0.0350493686052974  -0.465211076182388   
1   0.661695924845707    0.435477208966341  137596574254306,00   
2  -0.294166317554753   -0.932391057274991   0.172726295799422   
3   0.573574068424352    0.176967718048195  -0.436206883597401   
4   -0.37906830709218   -0.704181032215427  -0.656804756348389   

                   V24                 V25                 V26  \
0    0.320198198514526  0.0445191674731724   0.177839798284401   
1   -0.293803152734021   0.279798031841214  -0.145361714815161   
2  -0.0873295379700724  -0.156114264651172  -0.542627889040196   
3  -0.0535018648884285   0.252405261951833  -0.657487754764504   
4  -163265295692929,00  148890144838237,00   0.566797273468934   

                   V27                 V28  Amount Class  
0    0.261145002567677  -0.143275874698919    0.00     1  
1   -0.252773122530705  0.0357642251788156  529.00     1  
2   0.0395659889264757  -0.153028796529788  239.93     1  
3   -0.827135714578603   0.849573379985768   59.00     1  
4  -0.0100162234965625   0.146792734916988    1.00     1  

[5 rows x 31 columns]

In [11]:
#verificação se existem valores nulos
data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [17]:
#transformando os valores com , para .
data = data.replace(',','.', regex=True)
data = data.astype(float)

In [23]:
#antes da validação da importância das features, vamos realizar um teste com as colunas originais
features = data.iloc[:,:-1].values
target = data.iloc[:,-1].values

In [24]:
features

array([[ 4.06000000e+02, -2.31222654e+13,  1.95199201e+14, ...,
         2.61145003e-01, -1.43275875e-01,  0.00000000e+00],
       [ 4.72000000e+02, -3.04354062e+13, -3.15730712e+14, ...,
        -2.52773123e-01,  3.57642252e-02,  5.29000000e+02],
       [ 4.46200000e+03, -2.30334957e+14,  1.75924746e+12, ...,
         3.95659889e-02, -1.53028797e-01,  2.39930000e+02],
       ...,
       [ 5.33000000e+02, -1.23353450e+14,  1.45320255e-01, ...,
         2.34284579e-01,  1.90521392e-01,  2.91360000e+02],
       [ 5.34000000e+02, -1.39326519e+13, -1.09556933e+14, ...,
        -8.63521425e-01, -5.19167901e-01,  2.50000000e+01],
       [ 5.35000000e+02, -8.66655167e-01,  1.02962058e+14, ...,
        -1.44101989e-01, -7.71636303e-02,  8.50000000e+00]])

In [25]:
target

array([1., 1., 1., ..., 0., 0., 0.])

In [50]:
#separação dos dados em treino e teste
x_train,x_test,y_train,y_test = train_test_split(features, target, test_size = 0.2, random_state = 42)

In [51]:
#criação e treino do modelo
RandomForest = RandomForestClassifier()
RandomForest.fit(x_train,y_train)

RandomForestClassifier()

In [52]:
#predição
forecast = RandomForest.predict(x_test)

In [58]:
len(x_train)

959

In [53]:
forecast

array([0., 0., 1., 1., 1., 0., 1., 0., 1., 0., 0., 1., 1., 0., 1., 1., 0.,
       0., 0., 1., 1., 0., 0., 1., 1., 1., 0., 0., 1., 0., 1., 0., 0., 0.,
       1., 0., 1., 1., 1., 0., 0., 1., 0., 1., 0., 1., 1., 1., 1., 1., 0.,
       0., 1., 1., 0., 1., 0., 0., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1.,
       0., 1., 1., 1., 0., 1., 1., 1., 1., 1., 0., 0., 0., 1., 0., 1., 0.,
       0., 0., 1., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0., 1., 1., 0., 1.,
       0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 1., 1., 0.,
       1., 0., 0., 0., 0., 1., 0., 1., 1., 0., 0., 1., 0., 1., 1., 0., 0.,
       0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0.,
       1., 0., 1., 1., 1., 0., 1., 0., 0., 0., 1., 1., 0., 1., 0., 0., 1.,
       0., 0., 1., 1., 1., 0., 1., 0., 1., 0., 0., 0., 1., 0., 1., 0., 0.,
       0., 1., 0., 0., 0., 1., 0., 1., 1., 1., 0., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0.,
       0., 0., 0., 1., 0.

In [54]:
y_test

array([0., 0., 1., 1., 1., 0., 1., 0., 1., 0., 0., 1., 1., 0., 1., 1., 0.,
       0., 0., 1., 1., 0., 0., 1., 1., 1., 0., 0., 1., 0., 1., 0., 0., 0.,
       1., 0., 1., 1., 1., 0., 0., 1., 0., 1., 0., 1., 1., 1., 1., 1., 0.,
       0., 1., 1., 0., 1., 0., 0., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1.,
       0., 1., 1., 1., 0., 1., 1., 1., 1., 1., 0., 0., 0., 1., 0., 1., 0.,
       0., 0., 1., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0., 1., 1., 0., 1.,
       0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 1., 1., 0.,
       1., 0., 0., 0., 0., 1., 0., 1., 1., 0., 0., 1., 0., 1., 1., 0., 0.,
       0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0.,
       1., 0., 1., 1., 1., 0., 1., 0., 0., 0., 1., 1., 0., 1., 0., 0., 1.,
       0., 0., 1., 1., 1., 0., 1., 0., 1., 0., 0., 0., 1., 0., 1., 0., 0.,
       0., 1., 0., 0., 0., 1., 0., 1., 1., 1., 0., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0.,
       0., 0., 0., 1., 0.

In [56]:
#verificação da taxa de acerto
accuracy_score(y_test,forecast)
print(f"A taxa de acerto do modelo é de {accuracy_score(y_test,forecast)*100}%")

A taxa de acerto do modelo é de 100.0%


In [62]:
#mesmo com a taxa de acerto em 100%, vamos verificar a importancia das colunas
forest = ExtraTreesClassifier()
forest.fit(x_train,y_train)

ExtraTreesClassifier()

In [66]:
importance = forest.feature_importances_
importance

array([0.28901927, 0.015342  , 0.01268959, 0.07549411, 0.04327435,
       0.00894638, 0.02226805, 0.02518719, 0.00663034, 0.02474683,
       0.06572561, 0.04873227, 0.09063743, 0.00269359, 0.10026565,
       0.00405622, 0.03862545, 0.04421506, 0.02344107, 0.01059082,
       0.00543323, 0.00591463, 0.00346876, 0.00481843, 0.00240899,
       0.00614824, 0.00262103, 0.01046835, 0.00228714, 0.00384989])

In [69]:
importance_sorted = np.argsort(importance)[::-1]

In [75]:
for i in importance_sorted:
    print(f"A importância da coluna {data.columns[i]} na posição {i} é de {importance[i]}")

A importância da coluna Time posição 0 é de 0.28901927434595054
A importância da coluna V14 posição 14 é de 0.10026565433086974
A importância da coluna V12 posição 12 é de 0.0906374328987862
A importância da coluna V3 posição 3 é de 0.07549411117698136
A importância da coluna V10 posição 10 é de 0.06572561163088537
A importância da coluna V11 posição 11 é de 0.04873227087216379
A importância da coluna V17 posição 17 é de 0.04421506155619719
A importância da coluna V4 posição 4 é de 0.04327434974120116
A importância da coluna V16 posição 16 é de 0.03862545117915018
A importância da coluna V7 posição 7 é de 0.025187185054330027
A importância da coluna V9 posição 9 é de 0.024746832287039295
A importância da coluna V18 posição 18 é de 0.023441074570420856
A importância da coluna V6 posição 6 é de 0.02226805185365725
A importância da coluna V1 posição 1 é de 0.015342002318093921
A importância da coluna V2 posição 2 é de 0.012689593845389771
A importância da coluna V19 posição 19 é de 0.0105